spring:
  application:
    name: Assets-Management-App
  datasource:
    url: jdbc:postgresql://localhost:5432/assetdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: vinayvastrakar13@gmail.com
    password: ywaqzzglegkqnayw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true